// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2N4EiJc8jEOavwaSeM2X0pOLr39UZGo',
    appId: '1:891054462025:web:c57ff3e42b250d01311b98',
    messagingSenderId: '891054462025',
    projectId: 'neu-fall-2024',
    authDomain: 'neu-fall-2024.firebaseapp.com',
    databaseURL: 'https://neu-fall-2024-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2024.appspot.com',
    measurementId: 'G-SM26T1G972',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkanM-oXIscJdqzV8axNlMUmMutrQGRU',
    appId: '1:891054462025:android:b156692253c07099311b98',
    messagingSenderId: '891054462025',
    projectId: 'neu-fall-2024',
    databaseURL: 'https://neu-fall-2024-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UmRsP6IkFpEiNjfTqsjnhW8gjyD4Yqo',
    appId: '1:891054462025:ios:6c3aa0cea559916c311b98',
    messagingSenderId: '891054462025',
    projectId: 'neu-fall-2024',
    databaseURL: 'https://neu-fall-2024-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2024.appspot.com',
    iosClientId: '891054462025-kgof5a41u92ndojfkj10e63ahpdmtpv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UmRsP6IkFpEiNjfTqsjnhW8gjyD4Yqo',
    appId: '1:891054462025:ios:383325588c9bd453311b98',
    messagingSenderId: '891054462025',
    projectId: 'neu-fall-2024',
    databaseURL: 'https://neu-fall-2024-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2024.appspot.com',
    iosClientId: '891054462025-j3pkqeo0p18b3kvmht9dmkbhrcp6g3th.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
